import './globals.css'
import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })
import localFont from '@next/font/local'

const font = localFont({
  src: [
    {
      path: '../../public/fonts/font1.ttf',
      weight: '400'
    },
    {
      path: '../../public/fonts/font2.ttf',
      weight: '700'
    }
  ],
  variable: '--myfont'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${font.variable} font-sans`}>{children}</body>
    </html>
  )
}
